version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"